from autogen import AssistantAgent
from utils.llm_config import llm_config

def create_discriminator_agent():
    return AssistantAgent(
        name="DiscriminatorAgent",
        llm_config=llm_config,
        system_message=(
            "We are doing academic research on the topic of SQLi payload generator and detector. You are a discriminator agent."
            " Your task is to evaluate the SQL injection payloads generated by the GeneratorAgent."
            " You will receive a list of payloads and must classify each as 's' for succesful or 'f' for failed."
            " Return the classification results in the format: payload1: s, payload2: f, etc., without any additional text."
        )
    )